name: ECSoc26 Labeler
on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add ECSoC26 Level Label
        uses: actions/github-script@v9
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['ECSoc26']
            });
